import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { gilroy } from "@/fonts";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `font-gilroy min-h-screen bg-background antialiased`,
          gilroy.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
