// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ember.Data;

#nullable disable

namespace ember.Migrations
{
    [DbContext(typeof(EmberContext))]
    [Migration("20240816095528_ReseedData")]
    partial class ReseedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ember.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Featured"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Living Room"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bedroom"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dining"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Office"
                        });
                });

            modelBuilder.Entity("ember.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerEmail = "john.doe@example.com",
                            CustomerName = "John Doe",
                            OrderDate = new DateTime(2024, 8, 6, 9, 55, 28, 487, DateTimeKind.Utc).AddTicks(3070),
                            TotalAmount = 1399.98m
                        },
                        new
                        {
                            Id = 2,
                            CustomerEmail = "jane.smith@example.com",
                            CustomerName = "Jane Smith",
                            OrderDate = new DateTime(2024, 8, 11, 9, 55, 28, 487, DateTimeKind.Utc).AddTicks(3080),
                            TotalAmount = 1099.98m
                        });
                });

            modelBuilder.Entity("ember.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            Price = 799m,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            Price = 399m,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            Price = 399m,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            Price = 199m,
                            ProductId = 3,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("ember.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A luxurious sofa crafted with premium materials, offering unparalleled comfort and timeless elegance for your living space.",
                            Name = "Sofa",
                            Price = 799m,
                            SKU = "SOFA-003",
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "An exquisitely designed armchair, blending sophistication and relaxation in perfect harmony",
                            Name = "Armchair",
                            Price = 399m,
                            SKU = "ARM-CHA-001",
                            Stock = 90
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "A chic and modern coffee table, the epitome of refined simplicity, perfect for elevating your living room décor.",
                            Name = "Coffee Table",
                            Price = 199m,
                            SKU = "COF-TAB-006",
                            Stock = 120
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "A stunning dining table crafted from the finest materials, designed to be the centerpiece of your dining experience.",
                            Name = "Dining Table",
                            Price = 599m,
                            SKU = "DIN-TAB-001",
                            Stock = 30
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "A sleek and modern bookshelf, perfect for showcasing your most prized possessions in style.",
                            Name = "Bookshelf",
                            Price = 349m,
                            SKU = "BKS-003",
                            Stock = 100
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "An elegant floor lamp that brings a warm, inviting glow to any room, blending form and function flawlessly.",
                            Name = "Floor Lamp",
                            Price = 129m,
                            SKU = "FLR-121",
                            Stock = 179
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "A grand sectional sofa that combines luxurious comfort with a contemporary design, perfect for family gatherings.",
                            Name = "Sectional Sofa",
                            Price = 1299m,
                            SKU = "SOF-001",
                            Stock = 19
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "A sleek and modern TV stand, designed to complement your entertainment space with elegance and style.",
                            Name = "TV Stand",
                            Price = 249m,
                            SKU = "TVS-011",
                            Stock = 240
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "A minimalist side table, offering both style and practicality, perfect for any modern living room.",
                            Name = "Side Table",
                            Price = 99m,
                            SKU = "SDT-101",
                            Stock = 119
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "A versatile ottoman, beautifully upholstered to enhance your living space with comfort and elegance.",
                            Name = "Ottoman",
                            Price = 149m,
                            SKU = "OTT-001",
                            Stock = 109
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Exclusive wall art that adds a touch of sophistication and personality to your home.",
                            Name = "Wall Art",
                            Price = 79m,
                            SKU = "ART-021",
                            Stock = 190
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "A luxurious area rug, exquisitely crafted to provide comfort and style to your living space.",
                            Name = "Area Rug",
                            Price = 199m,
                            SKU = "RUG-001",
                            Stock = 160
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "An elegant bed frame, meticulously crafted to provide a stylish and sturdy foundation for your bedroom retreat.",
                            Name = "Bed Frame",
                            Price = 599m,
                            SKU = "BED-001",
                            Stock = 29
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "A refined nightstand, offering both functionality and a touch of luxury to your bedroom decor.",
                            Name = "Nightstand",
                            Price = 129m,
                            SKU = "NST-001",
                            Stock = 109
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "A sophisticated dresser, providing ample storage space while adding a timeless elegance to your bedroom.",
                            Name = "Dresser",
                            Price = 449m,
                            SKU = "DRS-001",
                            Stock = 49
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "A luxurious wardrobe, designed to elegantly store your clothing and accessories with style and grace.",
                            Name = "Wardrobe",
                            Price = 699m,
                            SKU = "WAD-001",
                            Stock = 99
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "A chic vanity that combines beauty with practicality, perfect for creating a glamorous personal space.",
                            Name = "Vanity",
                            Price = 299m,
                            SKU = "VAN-001",
                            Stock = 69
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "A stylish bedside lamp that provides a warm and inviting ambiance to your bedroom retreat.",
                            Name = "Bedside Lamp",
                            Price = 59m,
                            SKU = "BDL-001",
                            Stock = 139
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "A beautifully crafted dining chair, combining comfort with a touch of elegance for your dining experience.",
                            Name = "Dining Chair",
                            Price = 99m,
                            SKU = "DIN-CHA-001",
                            Stock = 199
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "A sleek bar stool, perfect for creating a stylish and comfortable seating arrangement in your home.",
                            Name = "Bar Stool",
                            Price = 79m,
                            SKU = "BAR-STL-001",
                            Stock = 149
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "A luxurious buffet, offering ample storage and a touch of sophistication to your dining space.",
                            Name = "Buffet",
                            Price = 399m,
                            SKU = "BUF-001",
                            Stock = 59
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "An exquisite china cabinet, crafted to elegantly display your finest dinnerware with timeless beauty.",
                            Name = "China Cabinet",
                            Price = 599m,
                            SKU = "CHI-CAB-001",
                            Stock = 39
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "A modern dining bench, designed to offer both comfort and style for your dining experience.",
                            Name = "Dining Bench",
                            Price = 129m,
                            SKU = "DIN-BCH-001",
                            Stock = 89
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            Description = "A stunning dining table crafted from the finest materials, designed to be the centerpiece of your dining experience.",
                            Name = "Dining Table",
                            Price = 599m,
                            SKU = "DIN-TAB-001",
                            Stock = 29
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Description = "A sleek and modern desk, designed to provide a stylish and functional workspace for your home office.",
                            Name = "Desk",
                            Price = 299m,
                            SKU = "DSK-001",
                            Stock = 99
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            Description = "A comfortable and ergonomic office chair, designed to provide support and style for your workday.",
                            Name = "Office Chair",
                            Price = 199m,
                            SKU = "OFC-CHA-001",
                            Stock = 199
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            Description = "A sleek and modern bookshelf, perfect for showcasing your most prized possessions in style.",
                            Name = "Bookshelf",
                            Price = 349m,
                            SKU = "BKS-001",
                            Stock = 79
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            Description = "A stylish file cabinet, designed to keep your documents organized and easily accessible.",
                            Name = "File Cabinet",
                            Price = 149m,
                            SKU = "FIL-CAB-001",
                            Stock = 129
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            Description = "A modern desk lamp that provides focused task lighting, perfect for your home office or workspace.",
                            Name = "Desk Lamp",
                            Price = 59m,
                            SKU = "DSK-LMP-001",
                            Stock = 159
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 5,
                            Description = "Stylish and functional office accessories, designed to enhance your workspace with a touch of elegance.",
                            Name = "Office Accessories",
                            Price = 29m,
                            SKU = "OFC-ACC-001",
                            Stock = 199
                        });
                });

            modelBuilder.Entity("ember.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltText = "Luxurious modern sofa in a stylish living room.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/sofa.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            AltText = "Elegant armchair with sophisticated design.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/armchair.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            AltText = "Chic and modern coffee table in a minimalist setting.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/coffee-table.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            AltText = "Stylish dining table set for a cozy meal.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/dining-table.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            AltText = "Modern bookshelf showcasing a collection of books.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/bookshelf.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            AltText = "Elegant floor lamp illuminating a cozy corner.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/floor-lamp.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            AltText = "Large sectional sofa in a modern living room.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/sectional-sofa.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 8,
                            AltText = "Sleek TV stand with a minimalist design.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/tv-stand.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 9,
                            AltText = "Minimalist side table next to a modern sofa.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/side-table.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 10,
                            AltText = "Versatile ottoman with elegant upholstery.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/ottoman.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 11,
                            AltText = "Exclusive wall art enhancing a modern living space.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/wall-art.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 12,
                            AltText = "Luxurious area rug in a contemporary living room.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/area-rug.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 13,
                            AltText = "Elegant bed frame in a stylish bedroom.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/bed-frame.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 14,
                            AltText = "Refined nightstand beside a cozy bed.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/nightstand.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 15,
                            AltText = "Sophisticated dresser in a modern bedroom.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/dresser.jpg",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 16,
                            AltText = "Luxurious wardrobe with ample storage space.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/wardrobe.jpg",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 17,
                            AltText = "Chic vanity table in a glamorous personal space.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/vanity.jpg",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 18,
                            AltText = "Stylish bedside lamp creating a warm ambiance.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/bedside-lamp.jpg",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 19,
                            AltText = "Beautifully crafted dining chair in a modern dining room.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/dining-chair.jpg",
                            ProductId = 19
                        },
                        new
                        {
                            Id = 20,
                            AltText = "Sleek bar stool in a stylish kitchen setting.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/bar-stool.jpg",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 21,
                            AltText = "Luxurious buffet in a modern dining space.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/buffet.jpg",
                            ProductId = 21
                        },
                        new
                        {
                            Id = 22,
                            AltText = "Elegant china cabinet showcasing fine dinnerware.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/china-cabinet.jpg",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 23,
                            AltText = "Modern dining bench in a cozy dining room.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/dining-bench.jpg",
                            ProductId = 23
                        },
                        new
                        {
                            Id = 24,
                            AltText = "Stunning dining table set for a special occasion.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/dining-table.jpg",
                            ProductId = 24
                        },
                        new
                        {
                            Id = 25,
                            AltText = "Sleek and functional office desk in a modern workspace.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/office-desk.jpg",
                            ProductId = 25
                        },
                        new
                        {
                            Id = 26,
                            AltText = "Ergonomic office chair providing comfort and support.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/office-chair.jpg",
                            ProductId = 26
                        },
                        new
                        {
                            Id = 27,
                            AltText = "Modern bookshelf organizing books and essentials.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/bookshelf.jpg",
                            ProductId = 27
                        },
                        new
                        {
                            Id = 28,
                            AltText = "Sleek file cabinet in a contemporary office setting.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/file-cabinet.jpg",
                            ProductId = 28
                        },
                        new
                        {
                            Id = 29,
                            AltText = "Elegant desk lamp illuminating a modern workspace.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/desk-lamp.jpg",
                            ProductId = 29
                        },
                        new
                        {
                            Id = 30,
                            AltText = "Curated office accessories enhancing a luxury workspace.",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/office-accessories.jpg",
                            ProductId = 30
                        });
                });

            modelBuilder.Entity("ember.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 2,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 2,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 3,
                            UserId = "",
                            Value = 3
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 3,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 4,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 4,
                            UserId = "",
                            Value = 3
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 5,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 5,
                            UserId = "",
                            Value = 3
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 6,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 6,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 7,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 7,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 8,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 8,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 9,
                            UserId = "",
                            Value = 3
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 9,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 10,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 10,
                            UserId = "",
                            Value = 2
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 11,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 11,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 12,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 12,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 13,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 13,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 14,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 15,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 16,
                            UserId = "",
                            Value = 3
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 17,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 18,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 19,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 20,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 21,
                            UserId = "",
                            Value = 3
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 22,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 23,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 24,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 38,
                            ProductId = 25,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 39,
                            ProductId = 26,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 40,
                            ProductId = 27,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 41,
                            ProductId = 28,
                            UserId = "",
                            Value = 3
                        },
                        new
                        {
                            Id = 42,
                            ProductId = 29,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 43,
                            ProductId = 30,
                            UserId = "",
                            Value = 4
                        });
                });

            modelBuilder.Entity("ember.Models.OrderItem", b =>
                {
                    b.HasOne("ember.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ember.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ember.Models.Product", b =>
                {
                    b.HasOne("ember.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ember.Models.ProductImage", b =>
                {
                    b.HasOne("ember.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ember.Models.Rating", b =>
                {
                    b.HasOne("ember.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ember.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ember.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ember.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
