// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ember.Data;

#nullable disable

namespace ember.Migrations
{
    [DbContext(typeof(EmberContext))]
    [Migration("20240815180816_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ember.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Featured"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Living Room"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bedroom"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dining"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Office"
                        });
                });

            modelBuilder.Entity("ember.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerEmail = "john.doe@example.com",
                            CustomerName = "John Doe",
                            OrderDate = new DateTime(2024, 8, 5, 18, 8, 16, 266, DateTimeKind.Utc).AddTicks(1690),
                            TotalAmount = 1399.98m
                        },
                        new
                        {
                            Id = 2,
                            CustomerEmail = "jane.smith@example.com",
                            CustomerName = "Jane Smith",
                            OrderDate = new DateTime(2024, 8, 10, 18, 8, 16, 266, DateTimeKind.Utc).AddTicks(1710),
                            TotalAmount = 1099.98m
                        });
                });

            modelBuilder.Entity("ember.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            Price = 799m,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            Price = 399m,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            Price = 399m,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            Price = 199m,
                            ProductId = 3,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("ember.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "",
                            Image = "",
                            Name = "Sofa",
                            Price = 799m,
                            SKU = "SOFA-003",
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "",
                            Image = "",
                            Name = "Armchair",
                            Price = 399m,
                            SKU = "ARM-CHA-001",
                            Stock = 90
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "",
                            Image = "",
                            Name = "Coffee Table",
                            Price = 199m,
                            SKU = "COF-TAB-006",
                            Stock = 120
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "",
                            Image = "",
                            Name = "Dining Table",
                            Price = 599m,
                            SKU = "DIN-TAB-001",
                            Stock = 30
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "",
                            Image = "",
                            Name = "Bookshelf",
                            Price = 349m,
                            SKU = "BKS-003",
                            Stock = 100
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "",
                            Image = "",
                            Name = "Floor Lamp",
                            Price = 129m,
                            SKU = "FLR-121",
                            Stock = 179
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "",
                            Image = "",
                            Name = "Sectional Sofa",
                            Price = 1299m,
                            SKU = "SOF-001",
                            Stock = 19
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "",
                            Image = "",
                            Name = "TV Stand",
                            Price = 249m,
                            SKU = "TVS-011",
                            Stock = 240
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "",
                            Image = "",
                            Name = "Side Table",
                            Price = 99m,
                            SKU = "SDT-101",
                            Stock = 119
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "",
                            Image = "",
                            Name = "Ottoman",
                            Price = 149m,
                            SKU = "OTT-001",
                            Stock = 109
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "",
                            Image = "",
                            Name = "Wall Art",
                            Price = 79m,
                            SKU = "ART-021",
                            Stock = 190
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "",
                            Image = "",
                            Name = "Area Rug",
                            Price = 199m,
                            SKU = "RUG-001",
                            Stock = 160
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "",
                            Image = "",
                            Name = "Bed Frame",
                            Price = 599m,
                            SKU = "BED-001",
                            Stock = 29
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "",
                            Image = "",
                            Name = "Nightstand",
                            Price = 129m,
                            SKU = "NST-001",
                            Stock = 109
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "",
                            Image = "",
                            Name = "Dresser",
                            Price = 449m,
                            SKU = "DRS-001",
                            Stock = 49
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "",
                            Image = "",
                            Name = "Wardrobe",
                            Price = 699m,
                            SKU = "WAD-001",
                            Stock = 99
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "",
                            Image = "",
                            Name = "Vanity",
                            Price = 299m,
                            SKU = "VAN-001",
                            Stock = 69
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "",
                            Image = "",
                            Name = "Bedside Lamp",
                            Price = 59m,
                            SKU = "BDL-001",
                            Stock = 139
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "",
                            Image = "",
                            Name = "Dining Chair",
                            Price = 99m,
                            SKU = "DIN-CHA-001",
                            Stock = 199
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "",
                            Image = "",
                            Name = "Bar Stool",
                            Price = 79m,
                            SKU = "BAR-STL-001",
                            Stock = 149
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "",
                            Image = "",
                            Name = "Buffet",
                            Price = 399m,
                            SKU = "BUF-001",
                            Stock = 59
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "",
                            Image = "",
                            Name = "China Cabinet",
                            Price = 599m,
                            SKU = "CHI-CAB-001",
                            Stock = 39
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "",
                            Image = "",
                            Name = "Dining Bench",
                            Price = 129m,
                            SKU = "DIN-BCH-001",
                            Stock = 89
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            Description = "",
                            Image = "",
                            Name = "Dining Table",
                            Price = 599m,
                            SKU = "DIN-TAB-001",
                            Stock = 29
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Description = "",
                            Image = "",
                            Name = "Desk",
                            Price = 299m,
                            SKU = "DSK-001",
                            Stock = 99
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            Description = "",
                            Image = "",
                            Name = "Office Chair",
                            Price = 199m,
                            SKU = "OFC-CHA-001",
                            Stock = 199
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            Description = "",
                            Image = "",
                            Name = "Bookshelf",
                            Price = 349m,
                            SKU = "BKS-001",
                            Stock = 79
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            Description = "",
                            Image = "",
                            Name = "File Cabinet",
                            Price = 149m,
                            SKU = "FIL-CAB-001",
                            Stock = 129
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            Description = "",
                            Image = "",
                            Name = "Desk Lamp",
                            Price = 59m,
                            SKU = "DSK-LMP-001",
                            Stock = 159
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 5,
                            Description = "",
                            Image = "",
                            Name = "Office Accessories",
                            Price = 29m,
                            SKU = "OFC-ACC-001",
                            Stock = 199
                        });
                });

            modelBuilder.Entity("ember.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/sofa.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/armchair.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/coffee-table.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/dining-table.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/bookshelf.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/floor-lamp.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/sectional-sofa.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 8,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/tv-stand.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 9,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/side-table.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 10,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/ottoman.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 11,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/wall-art.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 12,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/area-rug.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 13,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/bed-frame.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 14,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/nightstand.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 15,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/dresser.jpg",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 16,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/wardrobe.jpg",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 17,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/vanity.jpg",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 18,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/bedside-lamp.jpg",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 19,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/dining-chair.jpg",
                            ProductId = 19
                        },
                        new
                        {
                            Id = 20,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/bar-stool.jpg",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 21,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/buffet.jpg",
                            ProductId = 21
                        },
                        new
                        {
                            Id = 22,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/china-cabinet.jpg",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 23,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/dining-bench.jpg",
                            ProductId = 23
                        },
                        new
                        {
                            Id = 24,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/dining-table.jpg",
                            ProductId = 24
                        },
                        new
                        {
                            Id = 25,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/office-desk.jpg",
                            ProductId = 25
                        },
                        new
                        {
                            Id = 26,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/office-chair.jpg",
                            ProductId = 26
                        },
                        new
                        {
                            Id = 27,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/bookshelf.jpg",
                            ProductId = 27
                        },
                        new
                        {
                            Id = 28,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/file-cabinet.jpg",
                            ProductId = 28
                        },
                        new
                        {
                            Id = 29,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/desk-lamp.jpg",
                            ProductId = 29
                        },
                        new
                        {
                            Id = 30,
                            AltText = "",
                            ImageUrl = "https://ember-kasubonteng.s3.eu-west-2.amazonaws.com/office-accessories.jpg",
                            ProductId = 30
                        });
                });

            modelBuilder.Entity("ember.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 2,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 2,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 3,
                            UserId = "",
                            Value = 3
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 3,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 4,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 4,
                            UserId = "",
                            Value = 3
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 5,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 5,
                            UserId = "",
                            Value = 3
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 6,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 6,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 7,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 7,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 8,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 8,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 9,
                            UserId = "",
                            Value = 3
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 9,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 10,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 10,
                            UserId = "",
                            Value = 2
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 11,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 11,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 12,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 12,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 13,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 13,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 14,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 15,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 16,
                            UserId = "",
                            Value = 3
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 17,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 18,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 19,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 20,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 21,
                            UserId = "",
                            Value = 3
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 22,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 23,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 24,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 38,
                            ProductId = 25,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 39,
                            ProductId = 26,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 40,
                            ProductId = 27,
                            UserId = "",
                            Value = 4
                        },
                        new
                        {
                            Id = 41,
                            ProductId = 28,
                            UserId = "",
                            Value = 3
                        },
                        new
                        {
                            Id = 42,
                            ProductId = 29,
                            UserId = "",
                            Value = 5
                        },
                        new
                        {
                            Id = 43,
                            ProductId = 30,
                            UserId = "",
                            Value = 4
                        });
                });

            modelBuilder.Entity("ember.Models.OrderItem", b =>
                {
                    b.HasOne("ember.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ember.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ember.Models.Product", b =>
                {
                    b.HasOne("ember.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ember.Models.ProductImage", b =>
                {
                    b.HasOne("ember.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ember.Models.Rating", b =>
                {
                    b.HasOne("ember.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ember.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ember.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ember.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
